### ISSUE TITLE
RSS feed crashes with more than 115 characters on Length of Description Snippet option

### ISSUE THREAD

**Issue by joelasso** [Rise-Vision/widget-rss#78] opened 2016-11-21 17:42 UTC
The user adds a rss feed to the bottom of this presentation
(https://apps.risevision.com/editor/workspace/234a7b29-9ef5-4452-8412-8202ccf2718a/?cid=791d85e8-1209-4ab6-8fe5-e121f8b2da8a)}
The user have the "_show description snippet_" option selected on the **data selection** submenu
They have 115 characters on **Length of Description Snippet** and the feed works on the editor, preview and display
they change to more than 115 characters and the feed stops working on editor, preview and display

**Comment by donnapep** [comment] 2016-11-22 13:55
@joelasso Thanks for reporting this. It's being caused by a limit to the number of characters that can be drawn to the canvas element that we use to implement scrolling. As a workaround, you can either decrease the snippet length or decrease the _Max Items in Queue_ setting.

**Comment by alanclayton** [comment] 2017-02-09 15:09
Won't fix

**Closed by alanclayton** 2017-02-09 15:09 UTC
