### ISSUE TITLE
When Widget is set to horizontal scrolling it will show blank if the Max Items in Queue is over a certain amount.

### ISSUE THREAD

**Issue by robb-price** [Rise-Vision/widget-rss#83] opened 2017-03-28 20:31 UTC
<b>How it works now:</b>
1. Add the http://rss.cnn.com/rss/cnn_topstories.rss rss feed to the Widget, set it to Scroll Left, and set 15 items in Max Items in Queue. Notice that nothing shows in the Widget in Editor or on the Display. 
2. Change the Transition to any other option, and the feed shows.

For further clarification: https://goo.gl/LdJlmn

<b>How it should work:</b>
Regardless of the amount of Max Items in Queue, the content should show in Editor and in the Presentation on a Display.

**Comment by robb-price** [comment] 2017-03-28 20:32
![](https://github.trello.services/images/mini-trello-icon.png) [Issue 83 - When Widget is set to horizontal scrolling it will show blank if the Max Items in Queue is over a certain amount.](https://trello.com/c/N04keqQo/3672-issue-83-when-widget-is-set-to-horizontal-scrolling-it-will-show-blank-if-the-max-items-in-queue-is-over-a-certain-amount)

**Comment by alanclayton** [comment] 2017-03-28 20:40
@robb-price does the data show if you reduce the number of items?

**Comment by alanclayton** [comment] 2017-03-28 20:46
@robb-price I believe the issue is when X number of items exceeds the max pixel width for html canvas. @rodrigopavezi @stulees Can you confirm? What is the max width?

**Comment by stulees** [comment] 2017-03-28 21:05
@alanclayton The max width/height of canvas in Chrome is 32,767 pixels. It is possible that the amount of content, in this case 15 items worth (title and snippet), exceeded that 32k. 
@robb-price Have you tried reducing the length of description snippet to something significantly smaller than 120 and test again?

**Comment by stulees** [comment] 2017-03-28 21:06
@robb-price Also try reducing by unselecting "Show Title"

**Comment by robb-price** [comment] 2017-03-29 17:39
@alanclayton @stulees It looks like both of those actions make this begin showing as expected. Any chance we can add this in as a message for the user when they select this option so they are not contacting support?

**Comment by alanclayton** [comment] 2017-04-06 01:55
Widget updated to log event. Will look to find fix if the issue turns out to be common. Closing issue.

**Closed by alanclayton** 2017-04-06 01:55 UTC
Labels: bug
